---
# handlers file for security_server


- name: Security Package Installed
  ansible.builtin.debug:
    msg: "{{ security_server_package }} Installed/Updated"

- name: Security Port Opened 
  ansible.builtin.debug:
    msg: "{{ security_server_port }} Opened Successfully"

- name: Restart the security service
  ansible.builtin.service:
    name: "{{ security_server_service }}"
    state: "{{ security_server_state }}"
